/**
 * Copyright (c) 2000-2014 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.jira.metrics.model.impl;

import com.liferay.jira.metrics.model.JiraComponent;
import com.liferay.jira.metrics.service.JiraComponentLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the JiraComponent service. Represents a row in the &quot;jirametrics_JiraComponent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JiraComponentImpl}.
 * </p>
 *
 * @author Manuel de la Peña
 * @see JiraComponentImpl
 * @see com.liferay.jira.metrics.model.JiraComponent
 * @generated
 */
public abstract class JiraComponentBaseImpl extends JiraComponentModelImpl
	implements JiraComponent {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a jira component model instance should use the {@link JiraComponent} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			JiraComponentLocalServiceUtil.addJiraComponent(this);
		}
		else {
			JiraComponentLocalServiceUtil.updateJiraComponent(this);
		}
	}
}