/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.jira.metrics.model.impl;

import com.liferay.jira.metrics.model.JiraProject;
import com.liferay.jira.metrics.model.JiraProjectModel;
import com.liferay.jira.metrics.model.JiraProjectSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the JiraProject service. Represents a row in the &quot;jirametrics_JiraProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.jira.metrics.model.JiraProjectModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JiraProjectImpl}.
 * </p>
 *
 * @author Manuel de la Peña
 * @see JiraProjectImpl
 * @see com.liferay.jira.metrics.model.JiraProject
 * @see com.liferay.jira.metrics.model.JiraProjectModel
 * @generated
 */
@JSON(strict = true)
public class JiraProjectModelImpl extends BaseModelImpl<JiraProject>
	implements JiraProjectModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a jira project model instance should use the {@link com.liferay.jira.metrics.model.JiraProject} interface instead.
	 */
	public static final String TABLE_NAME = "jirametrics_JiraProject";
	public static final Object[][] TABLE_COLUMNS = {
			{ "jiraProjectId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "label", Types.VARCHAR },
			{ "jiraProjectCode", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table jirametrics_JiraProject (jiraProjectId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,label VARCHAR(75) null,jiraProjectCode LONG)";
	public static final String TABLE_SQL_DROP = "drop table jirametrics_JiraProject";
	public static final String ORDER_BY_JPQL = " ORDER BY jiraProject.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY jirametrics_JiraProject.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.jira.metrics.model.JiraProject"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.jira.metrics.model.JiraProject"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.jira.metrics.model.JiraProject"),
			true);
	public static long JIRAPROJECTCODE_COLUMN_BITMASK = 1L;
	public static long LABEL_COLUMN_BITMASK = 2L;
	public static long NAME_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static JiraProject toModel(JiraProjectSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		JiraProject model = new JiraProjectImpl();

		model.setJiraProjectId(soapModel.getJiraProjectId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setLabel(soapModel.getLabel());
		model.setJiraProjectCode(soapModel.getJiraProjectCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<JiraProject> toModels(JiraProjectSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<JiraProject> models = new ArrayList<JiraProject>(soapModels.length);

		for (JiraProjectSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.jira.metrics.model.JiraProject"));

	public JiraProjectModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _jiraProjectId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setJiraProjectId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _jiraProjectId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return JiraProject.class;
	}

	@Override
	public String getModelClassName() {
		return JiraProject.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("jiraProjectId", getJiraProjectId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("label", getLabel());
		attributes.put("jiraProjectCode", getJiraProjectCode());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long jiraProjectId = (Long)attributes.get("jiraProjectId");

		if (jiraProjectId != null) {
			setJiraProjectId(jiraProjectId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String label = (String)attributes.get("label");

		if (label != null) {
			setLabel(label);
		}

		Long jiraProjectCode = (Long)attributes.get("jiraProjectCode");

		if (jiraProjectCode != null) {
			setJiraProjectCode(jiraProjectCode);
		}
	}

	@JSON
	@Override
	public long getJiraProjectId() {
		return _jiraProjectId;
	}

	@Override
	public void setJiraProjectId(long jiraProjectId) {
		_jiraProjectId = jiraProjectId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getLabel() {
		if (_label == null) {
			return StringPool.BLANK;
		}
		else {
			return _label;
		}
	}

	@Override
	public void setLabel(String label) {
		_columnBitmask |= LABEL_COLUMN_BITMASK;

		if (_originalLabel == null) {
			_originalLabel = _label;
		}

		_label = label;
	}

	public String getOriginalLabel() {
		return GetterUtil.getString(_originalLabel);
	}

	@JSON
	@Override
	public long getJiraProjectCode() {
		return _jiraProjectCode;
	}

	@Override
	public void setJiraProjectCode(long jiraProjectCode) {
		_columnBitmask |= JIRAPROJECTCODE_COLUMN_BITMASK;

		if (!_setOriginalJiraProjectCode) {
			_setOriginalJiraProjectCode = true;

			_originalJiraProjectCode = _jiraProjectCode;
		}

		_jiraProjectCode = jiraProjectCode;
	}

	public long getOriginalJiraProjectCode() {
		return _originalJiraProjectCode;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			JiraProject.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public JiraProject toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (JiraProject)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JiraProjectImpl jiraProjectImpl = new JiraProjectImpl();

		jiraProjectImpl.setJiraProjectId(getJiraProjectId());
		jiraProjectImpl.setUserId(getUserId());
		jiraProjectImpl.setUserName(getUserName());
		jiraProjectImpl.setCreateDate(getCreateDate());
		jiraProjectImpl.setModifiedDate(getModifiedDate());
		jiraProjectImpl.setName(getName());
		jiraProjectImpl.setLabel(getLabel());
		jiraProjectImpl.setJiraProjectCode(getJiraProjectCode());

		jiraProjectImpl.resetOriginalValues();

		return jiraProjectImpl;
	}

	@Override
	public int compareTo(JiraProject jiraProject) {
		int value = 0;

		value = getName().compareTo(jiraProject.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof JiraProject)) {
			return false;
		}

		JiraProject jiraProject = (JiraProject)obj;

		long primaryKey = jiraProject.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		JiraProjectModelImpl jiraProjectModelImpl = this;

		jiraProjectModelImpl._originalName = jiraProjectModelImpl._name;

		jiraProjectModelImpl._originalLabel = jiraProjectModelImpl._label;

		jiraProjectModelImpl._originalJiraProjectCode = jiraProjectModelImpl._jiraProjectCode;

		jiraProjectModelImpl._setOriginalJiraProjectCode = false;

		jiraProjectModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<JiraProject> toCacheModel() {
		JiraProjectCacheModel jiraProjectCacheModel = new JiraProjectCacheModel();

		jiraProjectCacheModel.jiraProjectId = getJiraProjectId();

		jiraProjectCacheModel.userId = getUserId();

		jiraProjectCacheModel.userName = getUserName();

		String userName = jiraProjectCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			jiraProjectCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			jiraProjectCacheModel.createDate = createDate.getTime();
		}
		else {
			jiraProjectCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			jiraProjectCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			jiraProjectCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		jiraProjectCacheModel.name = getName();

		String name = jiraProjectCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			jiraProjectCacheModel.name = null;
		}

		jiraProjectCacheModel.label = getLabel();

		String label = jiraProjectCacheModel.label;

		if ((label != null) && (label.length() == 0)) {
			jiraProjectCacheModel.label = null;
		}

		jiraProjectCacheModel.jiraProjectCode = getJiraProjectCode();

		return jiraProjectCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{jiraProjectId=");
		sb.append(getJiraProjectId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", label=");
		sb.append(getLabel());
		sb.append(", jiraProjectCode=");
		sb.append(getJiraProjectCode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.liferay.jira.metrics.model.JiraProject");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>jiraProjectId</column-name><column-value><![CDATA[");
		sb.append(getJiraProjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>label</column-name><column-value><![CDATA[");
		sb.append(getLabel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jiraProjectCode</column-name><column-value><![CDATA[");
		sb.append(getJiraProjectCode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = JiraProject.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			JiraProject.class
		};
	private long _jiraProjectId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _name;
	private String _originalName;
	private String _label;
	private String _originalLabel;
	private long _jiraProjectCode;
	private long _originalJiraProjectCode;
	private boolean _setOriginalJiraProjectCode;
	private long _columnBitmask;
	private JiraProject _escapedModel;
}