/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.jira.metrics.model.impl;

import com.liferay.jira.metrics.model.JiraProject;
import com.liferay.jira.metrics.service.JiraProjectLocalServiceUtil;

/**
 * The extended model base implementation for the JiraProject service. Represents a row in the &quot;jirametrics_JiraProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JiraProjectImpl}.
 * </p>
 *
 * @author Manuel de la Peña
 * @see JiraProjectImpl
 * @see com.liferay.jira.metrics.model.JiraProject
 * @generated
 */
public abstract class JiraProjectBaseImpl extends JiraProjectModelImpl
	implements JiraProject {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a jira project model instance should use the {@link JiraProject} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			JiraProjectLocalServiceUtil.addJiraProject(this);
		}
		else {
			JiraProjectLocalServiceUtil.updateJiraProject(this);
		}
	}
}