/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.jira.metrics.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JiraComponent service. Represents a row in the &quot;jirametrics_JiraComponent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.jira.metrics.model.impl.JiraComponentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.jira.metrics.model.impl.JiraComponentImpl}.
 * </p>
 *
 * @author Manuel de la Pe√±a
 * @see JiraComponent
 * @see com.liferay.jira.metrics.model.impl.JiraComponentImpl
 * @see com.liferay.jira.metrics.model.impl.JiraComponentModelImpl
 * @generated
 */
public interface JiraComponentModel extends BaseModel<JiraComponent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jira component model instance should use the {@link JiraComponent} interface instead.
	 */

	/**
	 * Returns the primary key of this jira component.
	 *
	 * @return the primary key of this jira component
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jira component.
	 *
	 * @param primaryKey the primary key of this jira component
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jira component ID of this jira component.
	 *
	 * @return the jira component ID of this jira component
	 */
	public long getJiraComponentId();

	/**
	 * Sets the jira component ID of this jira component.
	 *
	 * @param jiraComponentId the jira component ID of this jira component
	 */
	public void setJiraComponentId(long jiraComponentId);

	/**
	 * Returns the create date of this jira component.
	 *
	 * @return the create date of this jira component
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this jira component.
	 *
	 * @param createDate the create date of this jira component
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this jira component.
	 *
	 * @return the modified date of this jira component
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this jira component.
	 *
	 * @param modifiedDate the modified date of this jira component
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the uri of this jira component.
	 *
	 * @return the uri of this jira component
	 */
	@AutoEscape
	public String getUri();

	/**
	 * Sets the uri of this jira component.
	 *
	 * @param uri the uri of this jira component
	 */
	public void setUri(String uri);

	/**
	 * Returns the jira project ID of this jira component.
	 *
	 * @return the jira project ID of this jira component
	 */
	public long getJiraProjectId();

	/**
	 * Sets the jira project ID of this jira component.
	 *
	 * @param jiraProjectId the jira project ID of this jira component
	 */
	public void setJiraProjectId(long jiraProjectId);

	/**
	 * Returns the name of this jira component.
	 *
	 * @return the name of this jira component
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this jira component.
	 *
	 * @param name the name of this jira component
	 */
	public void setName(String name);

	/**
	 * Returns the disabled of this jira component.
	 *
	 * @return the disabled of this jira component
	 */
	public boolean getDisabled();

	/**
	 * Returns <code>true</code> if this jira component is disabled.
	 *
	 * @return <code>true</code> if this jira component is disabled; <code>false</code> otherwise
	 */
	public boolean isDisabled();

	/**
	 * Sets whether this jira component is disabled.
	 *
	 * @param disabled the disabled of this jira component
	 */
	public void setDisabled(boolean disabled);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JiraComponent jiraComponent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JiraComponent> toCacheModel();

	@Override
	public JiraComponent toEscapedModel();

	@Override
	public JiraComponent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}