/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.jira.metrics.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JiraDataRetrieve service. Represents a row in the &quot;jirametrics_JiraDataRetrieve&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.jira.metrics.model.impl.JiraDataRetrieveModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.jira.metrics.model.impl.JiraDataRetrieveImpl}.
 * </p>
 *
 * @author Manuel de la Peña
 * @see JiraDataRetrieve
 * @see com.liferay.jira.metrics.model.impl.JiraDataRetrieveImpl
 * @see com.liferay.jira.metrics.model.impl.JiraDataRetrieveModelImpl
 * @generated
 */
public interface JiraDataRetrieveModel extends BaseModel<JiraDataRetrieve> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jira data retrieve model instance should use the {@link JiraDataRetrieve} interface instead.
	 */

	/**
	 * Returns the primary key of this jira data retrieve.
	 *
	 * @return the primary key of this jira data retrieve
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jira data retrieve.
	 *
	 * @param primaryKey the primary key of this jira data retrieve
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jira data retrieve ID of this jira data retrieve.
	 *
	 * @return the jira data retrieve ID of this jira data retrieve
	 */
	public long getJiraDataRetrieveId();

	/**
	 * Sets the jira data retrieve ID of this jira data retrieve.
	 *
	 * @param jiraDataRetrieveId the jira data retrieve ID of this jira data retrieve
	 */
	public void setJiraDataRetrieveId(long jiraDataRetrieveId);

	/**
	 * Returns the create date of this jira data retrieve.
	 *
	 * @return the create date of this jira data retrieve
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this jira data retrieve.
	 *
	 * @param createDate the create date of this jira data retrieve
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this jira data retrieve.
	 *
	 * @return the modified date of this jira data retrieve
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this jira data retrieve.
	 *
	 * @param modifiedDate the modified date of this jira data retrieve
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this jira data retrieve.
	 *
	 * @return the status of this jira data retrieve
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this jira data retrieve.
	 *
	 * @param status the status of this jira data retrieve
	 */
	public void setStatus(String status);

	/**
	 * Returns the status description of this jira data retrieve.
	 *
	 * @return the status description of this jira data retrieve
	 */
	@AutoEscape
	public String getStatusDescription();

	/**
	 * Sets the status description of this jira data retrieve.
	 *
	 * @param statusDescription the status description of this jira data retrieve
	 */
	public void setStatusDescription(String statusDescription);

	/**
	 * Returns the day of this jira data retrieve.
	 *
	 * @return the day of this jira data retrieve
	 */
	public int getDay();

	/**
	 * Sets the day of this jira data retrieve.
	 *
	 * @param day the day of this jira data retrieve
	 */
	public void setDay(int day);

	/**
	 * Returns the month of this jira data retrieve.
	 *
	 * @return the month of this jira data retrieve
	 */
	public int getMonth();

	/**
	 * Sets the month of this jira data retrieve.
	 *
	 * @param month the month of this jira data retrieve
	 */
	public void setMonth(int month);

	/**
	 * Returns the year of this jira data retrieve.
	 *
	 * @return the year of this jira data retrieve
	 */
	public int getYear();

	/**
	 * Sets the year of this jira data retrieve.
	 *
	 * @param year the year of this jira data retrieve
	 */
	public void setYear(int year);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JiraDataRetrieve jiraDataRetrieve);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JiraDataRetrieve> toCacheModel();

	@Override
	public JiraDataRetrieve toEscapedModel();

	@Override
	public JiraDataRetrieve toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}