/**
 * Copyright (c) 2000-2014 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.jira.metrics.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JiraStatus service. Represents a row in the &quot;jirametrics_JiraStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.jira.metrics.model.impl.JiraStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.jira.metrics.model.impl.JiraStatusImpl}.
 * </p>
 *
 * @author Manuel de la Peña
 * @see JiraStatus
 * @see com.liferay.jira.metrics.model.impl.JiraStatusImpl
 * @see com.liferay.jira.metrics.model.impl.JiraStatusModelImpl
 * @generated
 */
public interface JiraStatusModel extends BaseModel<JiraStatus> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jira status model instance should use the {@link JiraStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this jira status.
	 *
	 * @return the primary key of this jira status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jira status.
	 *
	 * @param primaryKey the primary key of this jira status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jira status ID of this jira status.
	 *
	 * @return the jira status ID of this jira status
	 */
	public long getJiraStatusId();

	/**
	 * Sets the jira status ID of this jira status.
	 *
	 * @param jiraStatusId the jira status ID of this jira status
	 */
	public void setJiraStatusId(long jiraStatusId);

	/**
	 * Returns the create date of this jira status.
	 *
	 * @return the create date of this jira status
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this jira status.
	 *
	 * @param createDate the create date of this jira status
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this jira status.
	 *
	 * @return the modified date of this jira status
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this jira status.
	 *
	 * @param modifiedDate the modified date of this jira status
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the uri of this jira status.
	 *
	 * @return the uri of this jira status
	 */
	@AutoEscape
	public String getUri();

	/**
	 * Sets the uri of this jira status.
	 *
	 * @param uri the uri of this jira status
	 */
	public void setUri(String uri);

	/**
	 * Returns the name of this jira status.
	 *
	 * @return the name of this jira status
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this jira status.
	 *
	 * @param name the name of this jira status
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JiraStatus jiraStatus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JiraStatus> toCacheModel();

	@Override
	public JiraStatus toEscapedModel();

	@Override
	public JiraStatus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}