/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.jira.metrics.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JiraMetric service. Represents a row in the &quot;jirametrics_JiraMetric&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.jira.metrics.model.impl.JiraMetricModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.jira.metrics.model.impl.JiraMetricImpl}.
 * </p>
 *
 * @author Manuel de la Peña
 * @see JiraMetric
 * @see com.liferay.jira.metrics.model.impl.JiraMetricImpl
 * @see com.liferay.jira.metrics.model.impl.JiraMetricModelImpl
 * @generated
 */
public interface JiraMetricModel extends BaseModel<JiraMetric> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jira metric model instance should use the {@link JiraMetric} interface instead.
	 */

	/**
	 * Returns the primary key of this jira metric.
	 *
	 * @return the primary key of this jira metric
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jira metric.
	 *
	 * @param primaryKey the primary key of this jira metric
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jira metric ID of this jira metric.
	 *
	 * @return the jira metric ID of this jira metric
	 */
	public long getJiraMetricId();

	/**
	 * Sets the jira metric ID of this jira metric.
	 *
	 * @param jiraMetricId the jira metric ID of this jira metric
	 */
	public void setJiraMetricId(long jiraMetricId);

	/**
	 * Returns the user ID of this jira metric.
	 *
	 * @return the user ID of this jira metric
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this jira metric.
	 *
	 * @param userId the user ID of this jira metric
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this jira metric.
	 *
	 * @return the user uuid of this jira metric
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this jira metric.
	 *
	 * @param userUuid the user uuid of this jira metric
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this jira metric.
	 *
	 * @return the user name of this jira metric
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this jira metric.
	 *
	 * @param userName the user name of this jira metric
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this jira metric.
	 *
	 * @return the create date of this jira metric
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this jira metric.
	 *
	 * @param createDate the create date of this jira metric
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this jira metric.
	 *
	 * @return the modified date of this jira metric
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this jira metric.
	 *
	 * @param modifiedDate the modified date of this jira metric
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the jira project ID of this jira metric.
	 *
	 * @return the jira project ID of this jira metric
	 */
	public long getJiraProjectId();

	/**
	 * Sets the jira project ID of this jira metric.
	 *
	 * @param jiraProjectId the jira project ID of this jira metric
	 */
	public void setJiraProjectId(long jiraProjectId);

	/**
	 * Returns the jira component ID of this jira metric.
	 *
	 * @return the jira component ID of this jira metric
	 */
	public long getJiraComponentId();

	/**
	 * Sets the jira component ID of this jira metric.
	 *
	 * @param jiraComponentId the jira component ID of this jira metric
	 */
	public void setJiraComponentId(long jiraComponentId);

	/**
	 * Returns the jira status ID of this jira metric.
	 *
	 * @return the jira status ID of this jira metric
	 */
	public long getJiraStatusId();

	/**
	 * Sets the jira status ID of this jira metric.
	 *
	 * @param jiraStatusId the jira status ID of this jira metric
	 */
	public void setJiraStatusId(long jiraStatusId);

	/**
	 * Returns the priority of this jira metric.
	 *
	 * @return the priority of this jira metric
	 */
	public int getPriority();

	/**
	 * Sets the priority of this jira metric.
	 *
	 * @param priority the priority of this jira metric
	 */
	public void setPriority(int priority);

	/**
	 * Returns the day of this jira metric.
	 *
	 * @return the day of this jira metric
	 */
	public int getDay();

	/**
	 * Sets the day of this jira metric.
	 *
	 * @param day the day of this jira metric
	 */
	public void setDay(int day);

	/**
	 * Returns the month of this jira metric.
	 *
	 * @return the month of this jira metric
	 */
	public int getMonth();

	/**
	 * Sets the month of this jira metric.
	 *
	 * @param month the month of this jira metric
	 */
	public void setMonth(int month);

	/**
	 * Returns the year of this jira metric.
	 *
	 * @return the year of this jira metric
	 */
	public int getYear();

	/**
	 * Sets the year of this jira metric.
	 *
	 * @param year the year of this jira metric
	 */
	public void setYear(int year);

	/**
	 * Returns the total of this jira metric.
	 *
	 * @return the total of this jira metric
	 */
	public int getTotal();

	/**
	 * Sets the total of this jira metric.
	 *
	 * @param total the total of this jira metric
	 */
	public void setTotal(int total);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JiraMetric jiraMetric);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JiraMetric> toCacheModel();

	@Override
	public JiraMetric toEscapedModel();

	@Override
	public JiraMetric toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}