/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.jira.metrics.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JiraPriority service. Represents a row in the &quot;jirametrics_JiraPriority&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.jira.metrics.model.impl.JiraPriorityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.jira.metrics.model.impl.JiraPriorityImpl}.
 * </p>
 *
 * @author Manuel de la Peña
 * @see JiraPriority
 * @see com.liferay.jira.metrics.model.impl.JiraPriorityImpl
 * @see com.liferay.jira.metrics.model.impl.JiraPriorityModelImpl
 * @generated
 */
public interface JiraPriorityModel extends BaseModel<JiraPriority> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jira priority model instance should use the {@link JiraPriority} interface instead.
	 */

	/**
	 * Returns the primary key of this jira priority.
	 *
	 * @return the primary key of this jira priority
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jira priority.
	 *
	 * @param primaryKey the primary key of this jira priority
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jira priority ID of this jira priority.
	 *
	 * @return the jira priority ID of this jira priority
	 */
	public long getJiraPriorityId();

	/**
	 * Sets the jira priority ID of this jira priority.
	 *
	 * @param jiraPriorityId the jira priority ID of this jira priority
	 */
	public void setJiraPriorityId(long jiraPriorityId);

	/**
	 * Returns the create date of this jira priority.
	 *
	 * @return the create date of this jira priority
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this jira priority.
	 *
	 * @param createDate the create date of this jira priority
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this jira priority.
	 *
	 * @return the modified date of this jira priority
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this jira priority.
	 *
	 * @param modifiedDate the modified date of this jira priority
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the value of this jira priority.
	 *
	 * @return the value of this jira priority
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this jira priority.
	 *
	 * @param value the value of this jira priority
	 */
	public void setValue(String value);

	/**
	 * Returns the name of this jira priority.
	 *
	 * @return the name of this jira priority
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this jira priority.
	 *
	 * @param name the name of this jira priority
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JiraPriority jiraPriority);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JiraPriority> toCacheModel();

	@Override
	public JiraPriority toEscapedModel();

	@Override
	public JiraPriority toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}